# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:4000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=testdb
    networks:
      - app_network

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  db-data:
